### ISSUE TITLE
Hmisc will no longer export label<-.data.frame

### ISSUE THREAD

**Issue by harrelfe** [MangoTheCat/SASxport#12]
These lines in `NAMESPACE` are not needed and conflict with an upcoming release of `Hmisc`:

importFrom(Hmisc,"label<-")
importFrom(Hmisc,"label<-.data.frame")
importFrom(Hmisc,"label<-.default")

Please fix as soon as possible so that I can upload a much needed update of `Hmisc` to CRAN.  You should just import `label`, and methods will work automatically without import.

Thanks very much.

**Comment by owenjonesuob** [comment]
Hi @harrelfe - apologies for the delay in getting to this. We're in the process of revamping the package and will push an update as soon as possible.

**Comment by harrelfe** [comment]
Fantastic - thanks very much
Frank

------------------------------
Frank E Harrell Jr      Professor      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*

**Comment by owenjonesuob** [comment]
Fixed in v1.5.7 - see https://github.com/warnes/SASxport/pull/1
