### ISSUE TITLE
Deprecate this repository in favor of warnes/SASxport?

### ISSUE THREAD

**Issue by warnes** [MangoTheCat/SASxport#16]
@dougmet @owenjonesuob.  As you've noted, I'm now maintaining SASxport at warnes/SASxport.   

Could/should this be made even more explicit by 'cleaning' out this repository and just leaving a minimal README.md telling people to use the one at warnes/SASxport?

**Comment by dougmet** [comment]
Yes I’d be happy to leave only a readme with a link. We’ll refork if we ever want to contribute.

**Comment by owenjonesuob** [comment]
Agreed, seems sensible to clear this repo out, especially since changes made here were integrated into SASxport in v1.5.4.

**Comment by dougmet** [comment]
Closed by #17
