### ISSUE TITLE
read.xport fails with error "SAS transfer file has incorrect library header"

### ISSUE THREAD

**Issue by mtandp** [MangoTheCat/SASxport#7]
The read.xport function fails with the error message "SAS transfer file has incorrect library header" when reading the attached file. The same file opens fine in SAS and the SAS Universial Viewer. Somer more investigation found that the error seems to be caused by using '00'x padding, where a file that was read and saved in SAS uses '20'x for padding the 80 character records. I understand that '00'x padding is compliant with the specification of xpt files, but because SAS is forgiving a different padding character it seems that an R package should do the same, no?
[SimplePlot_3Subjects.zip](https://github.com/MangoTheCat/SASxport/files/404731/SimplePlot_3Subjects.zip)

**Comment by shanmdphd** [comment]
This is probably due to R's locale setting. I solved this problem by adding these lines to `~/.Rprofile`.

    Sys.setenv(LANG = "en")
    Sys.setlocale("LC_MESSAGES", 'en_US.UTF-8')
    Sys.setlocale("LC_ALL", "en_US.UTF-8")

**Comment by mtandp** [comment]
Hmm, I get warnings when I apply these settings. I assume they might be working on a Unix computer. I am using Windows and the warning says something like "OS reports request to set locale to "en_US.UTF-8" cannot be honored". So, this doesn't help, sorry.

**Comment by mtandp** [comment]
I am back to the padding issue. A SAS colleague suggested that there are zeros (00x0 used for padding where a file that works uses '20'x  values.

**Comment by effbiae** [comment]
indeed, it appears that "os version" is padded with 0x00's rather than 0x20's in the library header (and member header?)

**Comment by rogerjdeangelis** [comment]
Thanks for the quick reply

SAS documents two 'transport formats'

Enhanced: Record Layout for a SAS Version 8 or 9 Data Set in SAS Transport
Format
http://support.sas.com/techsup/technote/ts140_2.pdf

and

SAS V5 Layout
https://support.sas.com/techsup/technote/ts140.pdf

Is there any interest in the newer format.

**Comment by mtandp** [comment]
I can't say in general. I am using xpt files in the context of CDISC and so far I was fine with v5. However, I know that there is discussion about other formats - including the newer SAS Transport. So, if you ask me, I suspect that there will be interest from the life science community.

**Comment by owenjonesuob** [comment]
Hi all! Thanks for your investigation into this. The latest version of this package (v1.5.7) can be found at https://github.com/warnes/SASxport - if the problem hasn't been addressed within the last couple of releases, please consider opening a new issue over there.
